import { auth } from "@/app/lib/auth";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers, { SessionProvider } from "./Providers";
import "./globals.css";
import Footer from "./ui/Footer";
import Header from "./ui/Header";
import Main from "./ui/Main";

const inter = Inter({ subsets: ["latin"] });
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" className=" h-full overflow-hidden relative">
      <body
        className={`${
          inter.className
        } ${"h-full overflow-auto relative bg-light text-dark dark:text-light dark:bg-dark"}`}
      >
        <SessionProvider session={session}>
          <Providers>
            <Header />
            <Main>{children}</Main>
            <Footer />
          </Providers>
        </SessionProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
