import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./Providers";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Main from "./components/Main";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" h-full overflow-hidden relative">
      <body className={`${inter.className} ${"h-full overflow-auto relative"}`}>
        <Providers>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
