/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    lyovsons: LyovsonAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    media: Media;
    topics: Topic;
    projects: Project;
    lyovsons: Lyovson;
    contacts: Contact;
    references: Reference;
    activities: Activity;
    notes: Note;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    lyovsons: LyovsonsSelect<false> | LyovsonsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: Lyovson & {
    collection: 'lyovsons';
  };
  jobs: {
    tasks: {
      generateEmbedding: TaskGenerateEmbedding;
      computeRecommendations: TaskComputeRecommendations;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      processPostEmbeddings: WorkflowProcessPostEmbeddings;
    };
  };
}
export interface LyovsonAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The main title of your post
   */
  title: string;
  /**
   * Main image used in cards and social sharing
   */
  featuredImage?: (number | null) | Media;
  /**
   * Brief description for previews and SEO
   */
  description?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * What type of content is this?
   */
  type: 'article' | 'review' | 'video' | 'podcast' | 'photo';
  /**
   * Rate from 1-10 stars
   */
  rating?: number | null;
  /**
   * What are you reviewing? (can select multiple)
   */
  reference?: (number | Reference)[] | null;
  /**
   * YouTube, Vimeo, or other video embed URL
   */
  videoEmbedUrl?: string | null;
  /**
   * Spotify, Apple Podcasts, or other podcast embed URL
   */
  podcastEmbedUrl?: string | null;
  /**
   * Tag this post with relevant topics
   */
  topics?: (number | Topic)[] | null;
  /**
   * Group this post into a series or project (optional)
   */
  project?: (number | null) | Project;
  /**
   * People, companies, works, and web media referenced in this post
   */
  references?: (number | Reference)[] | null;
  /**
   * Notes that connect to this post
   */
  notesReferenced?: (number | Note)[] | null;
  /**
   * When this post should be published
   */
  publishedAt?: string | null;
  /**
   * Who authored this post
   */
  authors?: (number | Lyovson)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
        username?: string | null;
      }[]
    | null;
  /**
   * Pre-computed recommended post IDs based on semantic similarity
   */
  recommended_post_ids?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Plain text extracted from rich text content for full-text search indexing
   */
  content_text?: string | null;
  /**
   * Vector embedding for semantic search (pgvector format)
   */
  embedding_vector?: string | null;
  embedding_model?: string | null;
  embedding_dimensions?: number | null;
  embedding_generated_at?: string | null;
  embedding_text_hash?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Unified references for people, companies, works, and web media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  /**
   * The title or name of this reference
   */
  title: string;
  /**
   * What type of reference is this?
   */
  type:
    | 'book'
    | 'movie'
    | 'tvShow'
    | 'videoGame'
    | 'music'
    | 'podcast'
    | 'series'
    | 'person'
    | 'company'
    | 'website'
    | 'article'
    | 'video'
    | 'repository'
    | 'tool'
    | 'social'
    | 'other';
  /**
   * Image for this reference (cover, photo, logo, etc.)
   */
  image: number | Media;
  /**
   * Brief description or summary
   */
  description?: string | null;
  /**
   * ISBN number
   */
  isbn?: string | null;
  /**
   * Publisher name
   */
  publisher?: string | null;
  /**
   * Number of pages
   */
  pageCount?: number | null;
  /**
   * Language
   */
  language?: string | null;
  /**
   * Book format
   */
  format?: ('hardcover' | 'paperback' | 'ebook' | 'audiobook') | null;
  /**
   * Series this item belongs to
   */
  series?: (number | null) | Reference;
  /**
   * Runtime in minutes
   */
  runtime?: number | null;
  /**
   * MPAA rating
   */
  mpaaRating?: ('g' | 'pg' | 'pg13' | 'r' | 'nc17' | 'nr') | null;
  /**
   * Network or streaming service
   */
  networkOrService?: string | null;
  /**
   * Show status
   */
  status?: ('ongoing' | 'ended' | 'cancelled') | null;
  /**
   * Season number
   */
  seasonNumber?: number | null;
  /**
   * Episode number
   */
  episodeNumber?: number | null;
  /**
   * Gaming platforms
   */
  platforms?: ('pc' | 'playstation' | 'xbox' | 'switch' | 'mobile' | 'vr')[] | null;
  /**
   * ESRB rating
   */
  esrbRating?: ('e' | 'e10' | 't' | 'm' | 'ao') | null;
  /**
   * Metacritic score
   */
  metacriticScore?: number | null;
  /**
   * Game developer
   */
  developer?: string | null;
  /**
   * Album this song belongs to
   */
  album?: (number | null) | Reference;
  /**
   * Track number
   */
  trackNumber?: number | null;
  /**
   * Record label
   */
  label?: string | null;
  /**
   * Barcode/UPC
   */
  barcode?: string | null;
  /**
   * Podcast show this episode belongs to
   */
  show?: (number | null) | Reference;
  /**
   * What roles does this person have?
   */
  roles?: ('author' | 'director' | 'actor' | 'musician' | 'developer' | 'host' | 'publicFigure')[] | null;
  /**
   * Birth date
   */
  birthDate?: string | null;
  /**
   * Death date
   */
  deathDate?: string | null;
  /**
   * Nationality
   */
  nationality?: string | null;
  /**
   * Personal or professional website
   */
  website?: string | null;
  /**
   * Social media links and profiles
   */
  socialLinks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Industry
   */
  industry?: string | null;
  /**
   * Founded date
   */
  foundedDate?: string | null;
  /**
   * URL for this web/media reference
   */
  url?: string | null;
  /**
   * Site or platform name
   */
  siteName?: string | null;
  /**
   * Article author
   */
  author?: string | null;
  /**
   * Publication date
   */
  publishedAt?: string | null;
  /**
   * Video platform (YouTube, Vimeo, etc.)
   */
  platform?: string | null;
  /**
   * Video ID
   */
  videoId?: string | null;
  /**
   * Additional links (purchase, streaming, etc.)
   */
  links?:
    | {
        label: string;
        url: string;
        kind?: ('purchase' | 'streaming' | 'official' | 'social' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * External service IDs
   */
  externalIds?: {
    /**
     * IMDB ID
     */
    imdbId?: string | null;
    /**
     * TVDB ID
     */
    tvdbId?: string | null;
    /**
     * Spotify ID
     */
    spotifyId?: string | null;
    /**
     * Apple Music ID
     */
    appleMusicId?: string | null;
    /**
     * Spotify URL
     */
    spotifyUrl?: string | null;
    /**
     * Apple Podcasts URL
     */
    applePodcastsUrl?: string | null;
    /**
     * Website URL
     */
    websiteUrl?: string | null;
    /**
     * Steam ID
     */
    steamId?: string | null;
    /**
     * IGDB ID
     */
    igdbId?: string | null;
    /**
     * Google Books ID
     */
    googleBooksId?: string | null;
  };
  /**
   * Tags for this reference
   */
  tags?: string[] | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Hex color code (e.g. #FF0000). Leave empty to inherit from parent.
   */
  color?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Topic;
  breadcrumbs?:
    | {
        doc?: (number | null) | Topic;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * The Audience ID from Resend for managing newsletter subscriptions.
   */
  resendAudienceId?: string | null;
  /**
   * List of contacts associated with this project.
   */
  contacts?: (number | Contact)[] | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Token used for email confirmation
   */
  confirmationToken?: string | null;
  /**
   * When the confirmation token expires
   */
  confirmationExpiry?: string | null;
  /**
   * Indicates if the contact has unsubscribed.
   */
  unsubscribed?: boolean | null;
  status?: ('pending' | 'active' | 'unsubscribed') | null;
  /**
   * Legacy field: Optional project association for historical data.
   */
  project?: (number | null) | Project;
  /**
   * The unique Contact ID from Resend.
   */
  resendContactId?: string | null;
  /**
   * The date and time the contact subscribed.
   */
  subscribedAt?: string | null;
  /**
   * Optional notes about the contact.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  /**
   * The main title of your note
   */
  title: string;
  /**
   * What type of note is this?
   */
  type: 'quote' | 'thought';
  /**
   * Who wrote this note?
   */
  author: 'rafa' | 'jess';
  /**
   * Who can see this note?
   */
  visibility: 'public' | 'private';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * What reference is this quote from?
   */
  sourceReference?: (number | null) | Reference;
  /**
   * Who said this quote? (e.g., author name, speaker)
   */
  quotedPerson?: string | null;
  /**
   * Page number, timestamp, or location reference
   */
  pageNumber?: string | null;
  /**
   * What topics does this note cover?
   */
  topics?: (number | Topic)[] | null;
  /**
   * Connect this note to other content in your knowledge base
   */
  connections?:
    | (
        | {
            relationTo: 'posts';
            value: number | Post;
          }
        | {
            relationTo: 'references';
            value: number | Reference;
          }
        | {
            relationTo: 'notes';
            value: number | Note;
          }
      )[]
    | null;
  /**
   * When this note should be published
   */
  publishedAt?: string | null;
  /**
   * Vector embedding for semantic search (pgvector format)
   */
  embedding_vector?: string | null;
  embedding_model?: string | null;
  embedding_dimensions?: number | null;
  embedding_generated_at?: string | null;
  embedding_text_hash?: string | null;
  /**
   * Plain text extracted from rich text content for full-text search indexing
   */
  content_text?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Lyovson family members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lyovsons".
 */
export interface Lyovson {
  id: number;
  /**
   * Profile picture for this user
   */
  avatar?: (number | null) | Media;
  /**
   * Preferred font family for this user's page
   */
  font?: ('sans' | 'serif' | 'mono') | null;
  /**
   * Full name of the user
   */
  name: string;
  username: string;
  /**
   * A short tagline or quote (like X/Facebook bio)
   */
  quote?: string | null;
  /**
   * A brief biography or description about this user
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Social media profiles and links
   */
  socialLinks?:
    | {
        platform: 'x' | 'linkedin' | 'github' | 'instagram' | 'facebook' | 'youtube' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Log reading, watching, listening, and playing activities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  /**
   * What are you reading/watching/listening to/playing?
   */
  reference: number | Reference;
  /**
   * Type of activity
   */
  activityType: 'read' | 'watch' | 'listen' | 'play';
  /**
   * Who participated in this activity?
   */
  participants?: (number | Lyovson)[] | null;
  /**
   * When did you start?
   */
  startedAt?: string | null;
  /**
   * When did you finish?
   */
  finishedAt?: string | null;
  /**
   * Who can see this activity?
   */
  visibility?: ('public' | 'private') | null;
  /**
   * Your thoughts, review, or notes about this activity
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ratings from family members (out of 10)
   */
  ratings?:
    | {
        /**
         * Who is rating this?
         */
        lyovson: number | Lyovson;
        /**
         * Rating out of 10
         */
        rating: number;
        /**
         * Optional comment about the rating
         */
        comment?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When this activity should be published
   */
  publishedAt?: string | null;
  slugSource?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  /**
   * Vector embedding for semantic search (pgvector format)
   */
  embedding_vector?: string | null;
  embedding_model?: string | null;
  embedding_dimensions?: number | null;
  embedding_generated_at?: string | null;
  embedding_text_hash?: string | null;
  /**
   * Plain text extracted from activity content for full-text search indexing
   */
  content_text?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  topics?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateEmbedding' | 'computeRecommendations';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'processPostEmbeddings' | null;
  taskSlug?: ('inline' | 'generateEmbedding' | 'computeRecommendations') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'lyovsons';
        value: number | Lyovson;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'lyovsons';
    value: number | Lyovson;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'lyovsons';
    value: number | Lyovson;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  featuredImage?: T;
  description?: T;
  content?: T;
  type?: T;
  rating?: T;
  reference?: T;
  videoEmbedUrl?: T;
  podcastEmbedUrl?: T;
  topics?: T;
  project?: T;
  references?: T;
  notesReferenced?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
        username?: T;
      };
  recommended_post_ids?: T;
  content_text?: T;
  embedding_vector?: T;
  embedding_model?: T;
  embedding_dimensions?: T;
  embedding_generated_at?: T;
  embedding_text_hash?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  color?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  resendAudienceId?: T;
  contacts?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lyovsons_select".
 */
export interface LyovsonsSelect<T extends boolean = true> {
  avatar?: T;
  font?: T;
  name?: T;
  username?: T;
  quote?: T;
  bio?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  confirmationToken?: T;
  confirmationExpiry?: T;
  unsubscribed?: T;
  status?: T;
  project?: T;
  resendContactId?: T;
  subscribedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  image?: T;
  description?: T;
  isbn?: T;
  publisher?: T;
  pageCount?: T;
  language?: T;
  format?: T;
  series?: T;
  runtime?: T;
  mpaaRating?: T;
  networkOrService?: T;
  status?: T;
  seasonNumber?: T;
  episodeNumber?: T;
  platforms?: T;
  esrbRating?: T;
  metacriticScore?: T;
  developer?: T;
  album?: T;
  trackNumber?: T;
  label?: T;
  barcode?: T;
  show?: T;
  roles?: T;
  birthDate?: T;
  deathDate?: T;
  nationality?: T;
  website?: T;
  socialLinks?: T;
  industry?: T;
  foundedDate?: T;
  url?: T;
  siteName?: T;
  author?: T;
  publishedAt?: T;
  platform?: T;
  videoId?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        kind?: T;
        id?: T;
      };
  externalIds?:
    | T
    | {
        imdbId?: T;
        tvdbId?: T;
        spotifyId?: T;
        appleMusicId?: T;
        spotifyUrl?: T;
        applePodcastsUrl?: T;
        websiteUrl?: T;
        steamId?: T;
        igdbId?: T;
        googleBooksId?: T;
      };
  tags?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  reference?: T;
  activityType?: T;
  participants?: T;
  startedAt?: T;
  finishedAt?: T;
  visibility?: T;
  notes?: T;
  ratings?:
    | T
    | {
        lyovson?: T;
        rating?: T;
        comment?: T;
        id?: T;
      };
  publishedAt?: T;
  slugSource?: T;
  slug?: T;
  slugLock?: T;
  embedding_vector?: T;
  embedding_model?: T;
  embedding_dimensions?: T;
  embedding_generated_at?: T;
  embedding_text_hash?: T;
  content_text?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  author?: T;
  visibility?: T;
  content?: T;
  sourceReference?: T;
  quotedPerson?: T;
  pageNumber?: T;
  topics?: T;
  connections?: T;
  publishedAt?: T;
  embedding_vector?: T;
  embedding_model?: T;
  embedding_dimensions?: T;
  embedding_generated_at?: T;
  embedding_text_hash?: T;
  content_text?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  topics?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateEmbedding".
 */
export interface TaskGenerateEmbedding {
  input: {
    collection: string;
    docId: number;
  };
  output: {
    success: boolean;
    skipped?: boolean | null;
    reason?: string | null;
    dimensions?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskComputeRecommendations".
 */
export interface TaskComputeRecommendations {
  input: {
    postId: number;
  };
  output: {
    success: boolean;
    count?: number | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowProcessPostEmbeddings".
 */
export interface WorkflowProcessPostEmbeddings {
  input: {
    postId: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeBlock".
 */
export interface YouTubeBlock {
  /**
   * Enter a YouTube URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ) or video ID
   */
  videoId: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  aspectRatio?: ('16:9' | '4:3' | '1:1') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtube';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "XPostBlock".
 */
export interface XPostBlock {
  /**
   * Enter an X (Twitter) post URL (e.g., https://x.com/username/status/123456789) or post ID
   */
  postId: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'xpost';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quote: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GIFBlock".
 */
export interface GIFBlock {
  mp4Url: string;
  webmUrl?: string | null;
  posterUrl: string;
  aspectRatio?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gif';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}